services:
  postgres:
    image: postgres:16-alpine
    container_name: skolska-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: skolska_platforma
      POSTGRES_USER: skolska
      POSTGRES_PASSWORD: skolska
      TZ: Europe/Belgrade
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skolska -d skolska_platforma"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: skolska-pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skolska.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"

  mailpit:
    image: axllent/mailpit:latest
    container_name: skolska-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
